name: 4-6

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0,6,12,18 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_folder: ['akun-4', 'akun-5', 'akun-6']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget google-chrome-stable

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib selenium requests selenium-stealth undetected-chromedriver

    - name: Download & Extract Files from Google Drive
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: python download_drive.py

    - name: Run All Bot Scripts in Target Folder
      run: |
        echo "Scanning all seofast_zhp.py inside '${{ matrix.target_folder }}'..."
        
        # Cari semua file seofast_zhp.py di dalam folder target & jalankan
        find ${{ matrix.target_folder }} -type f -name "seofast_zhp.py" | while read script; do
          dir=$(dirname "$script")
          echo "=========================================="
          echo "Running bot in: $dir"
          echo "=========================================="
          (cd "$dir" && python3 seofast_zhp.py) &
        done
        
        # Tunggu semua bot selesai berjalan
        wait
